name: CI
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  repro:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apple-actions/import-codesign-certs@5565bb656f60c98c8fc515f3444dd8db73545dc2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - run: ./repro.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist